# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/CMV2000_ctrl.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_assert_0_0/system_assert_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_assert_0_0 || ORIG_REF_NAME==system_assert_0_0} -quiet] -quiet

# XDC: d:/Files/VivadoProjects/CMV2000_ctrl/CMV2000_ctrl.gen/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Files/VivadoProjects/CMV2000_ctrl/CMV2000_ctrl.gen/sources_1/bd/system/system_ooc.xdc
